# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- name: Install influxdb server
  hosts: "{{host_inventory}}"
  vars_files:
    - vars/influxdb.yml
  vars:
    - combined_package_list: "{{ (default_packages|default([])) | union((install_packages_by_tag|default({})).influxdb|default([])) }}"
  roles:
    - ensure-interfaces-up
    - setup-web-proxy
    - { role: install-packages, package_list: "{{combined_package_list}}" }
    - role: add-package-repo
      package_name: influxdb
      repo_name: "InfluxDB Repository"
      repo_url: "https://repos.influxdata.com/rhel/$releasever/$basearch/stable"
      repo_key_url: "https://repos.influxdata.com/influxdb.key"
    - dn-influxdb
